"use strict";

// A reminder of the Fibonacci sequence
// fib(n) => fib(n-1) + fib(n-2)
// fib(0) == 0
// fib(1) == 1
// fib(2) == fib(1) + fib(0) == 1
// fib(3) == fib(2) + fib(1) == 2

// Store everything that we compute in the cache.
const cache = {
  "0": 0,
  "1": 1
};

// fib(n) => fib(n-1) + fib(n-2)
function fib(n) {
  if (`${n}` in cache) {
    return cache[`${n}`];

  } else {
    const val = fib(n-1) + fib(n-2);
    cache[`${n}`] = val;
    return val;
  }
}

// Basic, hacky test
console.log("Does fib() work? " + [
    (() => fib(0) === 0)
  , (() => fib(1) === 1)
  , (() => fib(2) === 1)
  , (() => fib(3) === 2)
  , (() => fib(4) === 3)
].every(f => f()))


const MAX_VALUE = 4000000;

let value = 0;
let term = 0;
let sum = 0;

while (true) {
  value = fib(term);

  if (value > MAX_VALUE) {
    break;

} else {
    // if the value is even, add it to the total
    if (value % 2 === 0) {
      sum += value; 
    }

    term++;
  }
}

console.log(`We did ${term} fibs, and the answer was ${sum}`);
console.log(`The highest value was ${value}, which was higher than ${MAX_VALUE}, so we stopped`);
console.log(`The penultimate value was ${fib(term-1)}`);

/**
I found this problem to be ambiguously worded:

"Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms."

So, firstly, starting with 1 and 2 the first terms are 1, and 1 again: fib(2) => fib(1) + fib(0) == 1 + 0 == 1.  So that threw me a bit.

Secondly, the words `term` and `value` are used interchangably.  The text says "by considering the terms whose values... find the sum of the even-valued terms."
What it wants us to do is to sum all of the even-valued /values/ (as long as the value is less than 4 million).  The first sentence uses the word `term` to describe
the values

In my opinion, the second sentence should read:
"By considering the terms in the Fibonacci sequence that do not exceed four million, find the sum of the even terms".

The puzzle is that simple: sum(fib(n), where fib(n) < 4 million and is even), for all positive integer values of n

*/

